site_name: Sduino
site_description: Programming the STM8S the Arduino way
site_author: Michael Mayer
repo_url: 'https://github.com/tenbaht/sduino'
pages:
    - User Guide:
        - Overview: 'index.md'
        - Installation: 'install.md'
        - Using the SDCC compiler: 'sdcc.md'
        - Using the SPL with SDCC and sduino: 'spl.md'
        - C preprocessor macro magic: 'macro.md'
    - Libraries:
        - API description and migration guidelines: api.md
#	- Standard Arduino functions:
        - HardwareSerial: api/HardwareSerial.md
        - SPI: api/SPI.md
        - I2C: api/I2C.md
        - LiquidCrystal character LCD library: api/LiquidCrystal.md
        - PCD8544 libray for Nokia 5110-like graphical LCDs: api/PCD8544.md
        - Mini_SSD1306 library for monochrome OLED-displays: api/Mini_SSD1306.md
        - Stepper library: api/Stepper.md
        - Servo library: api/Servo.md
    - Hardware:
        - Flash tool: hardware/flashtool.md
        - List of supported boards: hardware.md
        - Ways to define a pin mapping: 'hardware/pin_mapping.md'
        - 'Generic STM8S103 breakout board (stm8blue)': hardware/stm8blue.md
        - 'ESP14: Wifi board, STM8S003': hardware/esp14.md
        - 'STM8S105Discovery: Evaluation board made my ST': hardware/stm8sdiscovery.md
    - About: about.md

#- theme: amelia
#+++ theme: bootstrap		leicht, elegant
#+ theme: cerulean
#+++ theme: cosmo		elegant, ausgewogen
#- theme: cyborg		zu starker Kontrast
#++ theme: flatly		grau-blau
#++ theme: journal		Überschriften evtl. etwas zu schwer
#+++ theme: mkdocs		leicht, elegant. Wie Bootstrap. Mit Search
#+ theme: readable
#o theme: readthedocs		komplette Übersicht, Suche
#++ theme: simplex		elegant, Schrift evtl. etwas zu klein
#- theme: slate			zu starker Kontrast
#++ theme: spacelab		elegant und leicht, grau
#+++ theme: united		Orange. Ausgewogen.
#+++ theme: yeti		sehr gut. Leicht, elegant
# best: flatly, yeti (light typeface), cosmo, united, spacelab
# with search: mkdocs
theme: flatly
#theme: mkdocs
